import csv
import os


# =============================================================================
# Config
# =============================================================================

STARS_CSV = "stars_filtered.csv"
FAB_FILE = "constellationship.fab.txt"

STARS_OUT = "stars_data.h"
CONST_OUT = "constellation_data.h"

MAG_CUTOFF = 4.5


# =============================================================================
# Named star labels
# Maps raw catalogue names to common display names
# =============================================================================

STAR_LABELS = {
    "9Alp CMa": "Sirius",
    "Alp Car": "Canopus",
    "16Alp Boo": "Arcturus",
    "3Alp Lyr": "Vega",
    "13Alp Aur": "Capella",
    "19Bet Ori": "Rigel",
    "10Alp CMi": "Procyon",
    "58Alp Ori": "Betelgeuse",
    "21Alp Sco": "Antares",
    "78Bet Gem": "Pollux",
    "24Alp PsA": "Fomalhaut",
    "87Alp Tau": "Aldebaran",
    "67Alp Vir": "Spica",
    "32Alp Leo": "Regulus",
}


# =============================================================================
# Named star colours
# Colours are written as normal HEX first, then converted to RGB565 for TFT_eSPI
# =============================================================================

STAR_COLOURS_HEX = {
    "9Alp CMa": "#e8eeff",
    "Alp Car": "#fff8e8",
    "16Alp Boo": "#ffaa55",
    "3Alp Lyr": "#e0eaff",
    "13Alp Aur": "#ffeeaa",
    "19Bet Ori": "#c8d8ff",
    "10Alp CMi": "#fff5d8",
    "58Alp Ori": "#ff7733",
    "21Alp Sco": "#ff5522",
    "78Bet Gem": "#ffcc88",
    "24Alp PsA": "#eef2ff",
    "87Alp Tau": "#ff9944",
    "67Alp Vir": "#c0ccff",
    "32Alp Leo": "#ccd6ff",
}

DEFAULT_COLOUR_HEX = "#ffffff"


# =============================================================================
# Helper functions
# =============================================================================

def hex_to_rgb565(hex_str):
    # Remove the "#" from colour strings such as "#ffffff"
    hex_str = hex_str.lstrip("#")

    # Split the colour into red, green, and blue values
    r = int(hex_str[0:2], 16)
    g = int(hex_str[2:4], 16)
    b = int(hex_str[4:6], 16)

    # Convert RGB888 to RGB565
    # RGB888: 8 bits red, 8 bits green, 8 bits blue
    # RGB565: 5 bits red, 6 bits green, 5 bits blue
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def c_str(s):
    # Escape backslashes and double quotes so the label is safe in C++ strings
    return s.replace("\\", "\\\\").replace('"', '\\"')


# =============================================================================
# Generate stars_data.h
# =============================================================================

def generate_stars_header():
    stars = []

    # Read star data from the filtered CSV file
    with open(STARS_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        for row in reader:
            # Read magnitude
            try:
                mag = float(row["Mag"])
            except (ValueError, KeyError):
                continue

            # Skip stars that are dimmer than the cutoff
            if mag > MAG_CUTOFF:
                continue

            # Read RA and Dec
            try:
                ra = float(row["RA_deg"])
                dec = float(row["Dec"])
            except (ValueError, KeyError):
                continue

            # Read HIP ID
            # If there is no valid HIP ID, use 0
            hip_raw = row.get("HIP", "").strip()

            try:
                hip = int(float(hip_raw))
            except (ValueError, TypeError):
                hip = 0

            # Read catalogue name
            name_raw = row.get("Name", "").strip()

            # Convert raw name to common label if available
            label = STAR_LABELS.get(name_raw, "")

            # Get colour for named stars, otherwise use default white
            colour_hex = STAR_COLOURS_HEX.get(name_raw, DEFAULT_COLOUR_HEX)
            colour = hex_to_rgb565(colour_hex)

            # Store the star data
            stars.append({
                "hip": hip,
                "ra": ra,
                "dec": dec,
                "mag": mag,
                "colour": colour,
                "label": label,
            })

    # Sort stars from brightest to dimmest
    # Smaller magnitude number means brighter star
    stars.sort(key=lambda s: s["mag"])

    # Build the C++ header file line by line
    lines = []

    lines.append("// stars_data.h")
    lines.append("// AUTO-GENERATED by generate_headers.py")
    lines.append("// Do not edit this file manually.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("struct Star {")
    lines.append("    uint32_t hip;       // Hipparcos ID, 0 means no HIP ID")
    lines.append("    float    ra_deg;    // Right Ascension in degrees")
    lines.append("    float    dec_deg;   // Declination in degrees")
    lines.append("    float    mag;       // Visual magnitude")
    lines.append("    uint16_t colour;    // RGB565 colour")
    lines.append("    char     label[16]; // Common name, empty string if none")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint16_t STAR_COUNT = {len(stars)};")
    lines.append("")
    lines.append("// Store star data in flash memory to save RAM")
    lines.append("const Star STARS[] PROGMEM = {")

    # Add each star to the C++ array
    for s in stars:
        label_escaped = c_str(s["label"])[:15]

        if s["label"]:
            comment = f"  // {s['label']}"
        else:
            comment = ""

        lines.append(
            f'    {{ {s["hip"]:>6}, {s["ra"]:>10.4f}f, {s["dec"]:>9.4f}f, '
            f'{s["mag"]:>5.2f}f, 0x{s["colour"]:04X}, "{label_escaped}" }},{comment}'
        )

    lines.append("};")
    lines.append("")

    # Write the final header file
    with open(STARS_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[OK] {STARS_OUT} — {len(stars)} stars written")


# =============================================================================
# Generate constellation_data.h
# =============================================================================

def generate_constellation_header():
    segments = []

    # Skip constellation generation if the .fab file is missing
    if not os.path.exists(FAB_FILE):
        print(f"[WARN] {FAB_FILE} not found. Skipping constellation header.")
        return

    # Read constellation line data
    with open(FAB_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Skip blank lines and comments
            if not line or line.startswith("#"):
                continue

            parts = line.split()

            # Each valid line should contain:
            # constellation name, pair count, then HIP ID pairs
            if len(parts) < 3:
                continue

            try:
                pair_count = int(parts[1])
                hip_ids = [int(v) for v in parts[2:]]
            except ValueError:
                continue

            # Convert HIP ID pairs into line segments
            for i in range(0, pair_count * 2, 2):
                if i + 1 < len(hip_ids):
                    hip1 = hip_ids[i]
                    hip2 = hip_ids[i + 1]
                    segments.append((hip1, hip2))

    # Build the C++ header file line by line
    lines = []

    lines.append("// constellation_data.h")
    lines.append("// AUTO-GENERATED by generate_headers.py")
    lines.append("// Do not edit this file manually.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("struct ConstellationSegment {")
    lines.append("    uint32_t hip1;")
    lines.append("    uint32_t hip2;")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint16_t SEGMENT_COUNT = {len(segments)};")
    lines.append("")
    lines.append("// Store constellation line data in flash memory to save RAM")
    lines.append("const ConstellationSegment SEGMENTS[] PROGMEM = {")

    # Add each constellation line segment to the C++ array
    for hip1, hip2 in segments:
        lines.append(f"    {{ {hip1:>6}, {hip2:>6} }},")

    lines.append("};")
    lines.append("")

    # Write the final header file
    with open(CONST_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[OK] {CONST_OUT} — {len(segments)} segments written")


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    # Generate star data only if the filtered star CSV exists
    if not os.path.exists(STARS_CSV):
        print(f"[ERROR] {STARS_CSV} not found. Run star_catalogue_parser first.")
    else:
        generate_stars_header()

    # Generate constellation data
    generate_constellation_header()

    print("")
    print("Done! Copy stars_data.h and constellation_data.h into your Arduino sketch folder.")